### ISSUE TITLE
Wrong phone numbers throws error

### ISSUE THREAD

**Issue by guytepper** [dhershman1/phone-prettify#1]
Hi @dhershman1 ! Thanks for the great library.

When trying to normalize a wrong phone number, like `89139`, it throws the following error:  
`Uncaught TypeError: Cannot read property '0' of null`.

I think it's better to return the original number instead of throwing an error.  What do you think?

**Comment by dhershman1** [comment]
I don't see an issue in that at all really. I think that would be a nice enhancement for the module overall.

**Comment by dhershman1** [comment]
This is now available in the v1.5.0 release, do note this means that phone-prettify does do a extremely light validation check on the value passed in, this however is a simple regex length check to make sure they're all numbers and that they meet a minimum length for the phone numbers. 

Hope it works as requested!

**Comment by guytepper** [comment]
Thank you so much! 🙏
